"""
Alerting integrations for the GEWS monitoring pipeline.

Supports email (SMTP), Slack (webhook), and generic webhook alert
channels.  Each channel is configured under the top-level ``alerts:``
key in the site YAML config.  Secrets use ``${ENV_VAR}`` expansion.

Usage::

    from gews.alerts import AlertDispatcher

    dispatcher = AlertDispatcher.from_config(site_config)
    results = dispatcher.dispatch("WARNING", "Aletsch Glacier",
                                  "Anomalous acceleration detected...",
                                  {"max_zscore": 4.2, "n_flags": 3})
"""

from __future__ import annotations

import json
import logging
import os
import re
import smtplib
import ssl
import urllib.request
import urllib.error
from abc import ABC, abstractmethod
from datetime import datetime, timezone
from email.message import EmailMessage
from typing import Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Environment variable expansion
# ---------------------------------------------------------------------------

_ENV_PATTERN = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}")


def expand_env_vars(value: Any) -> Any:
    """Recursively expand ``${VAR_NAME}`` references in strings, dicts,
    and lists.  Missing variables expand to the empty string."""
    if isinstance(value, str):
        return _ENV_PATTERN.sub(
            lambda m: os.environ.get(m.group(1), ""), value
        )
    if isinstance(value, dict):
        return {k: expand_env_vars(v) for k, v in value.items()}
    if isinstance(value, list):
        return [expand_env_vars(item) for item in value]
    return value


# ---------------------------------------------------------------------------
# Channel base class
# ---------------------------------------------------------------------------


class AlertChannel(ABC):
    """Abstract base for a single notification channel."""

    name: str = "base"

    @abstractmethod
    def send(
        self,
        alert_level: str,
        site_name: str,
        message: str,
        details: dict[str, Any],
    ) -> None:
        """Send an alert through this channel.  Implementations should
        raise on transient errors so the dispatcher can log them."""


# ---------------------------------------------------------------------------
# Email channel
# ---------------------------------------------------------------------------


class EmailChannel(AlertChannel):
    """SMTP-based email alerts with HTML formatting."""

    name = "email"

    def __init__(
        self,
        smtp_host: str,
        smtp_port: int = 587,
        from_addr: str = "",
        to_addrs: list[str] | None = None,
        username: str = "",
        password: str = "",
        timeout: int = 30,
    ) -> None:
        self.smtp_host = smtp_host
        self.smtp_port = smtp_port
        self.from_addr = from_addr
        self.to_addrs = to_addrs or []
        self.username = username
        self.password = password
        self.timeout = timeout

    @classmethod
    def from_config(cls, cfg: dict) -> "EmailChannel | None":
        """Build from the ``alerts.email`` config section.  Returns None
        if required fields are missing."""
        host = cfg.get("smtp_host", "")
        if not host:
            logger.warning("Email channel: smtp_host missing; skipping")
            return None
        return cls(
            smtp_host=host,
            smtp_port=int(cfg.get("smtp_port", 587)),
            from_addr=cfg.get("from", ""),
            to_addrs=cfg.get("to", []),
            username=cfg.get("username", ""),
            password=cfg.get("password", ""),
            timeout=int(cfg.get("timeout", 30)),
        )

    # -- formatting --

    @staticmethod
    def _format_html(
        alert_level: str,
        site_name: str,
        message: str,
        details: dict[str, Any],
    ) -> str:
        level_colors = {
            "INFO": "#2196F3",
            "WARNING": "#FF9800",
            "CRITICAL": "#F44336",
        }
        color = level_colors.get(alert_level, "#607D8B")
        details_rows = "".join(
            f"<tr><td style='padding:4px 8px;font-weight:bold'>{k}</td>"
            f"<td style='padding:4px 8px'>{v}</td></tr>"
            for k, v in details.items()
        )
        return (
            f"<div style='font-family:sans-serif;max-width:600px'>"
            f"<h2 style='color:{color}'>[{alert_level}] GEWS Alert — {site_name}</h2>"
            f"<p>{message}</p>"
            f"<table style='border-collapse:collapse;width:100%'>"
            f"{details_rows}</table>"
            f"<hr><p style='font-size:0.85em;color:#888'>"
            f"Generated by GEWS at {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}"
            f"</p></div>"
        )

    @staticmethod
    def _format_plain(
        alert_level: str,
        site_name: str,
        message: str,
        details: dict[str, Any],
    ) -> str:
        lines = [
            f"[{alert_level}] GEWS Alert -- {site_name}",
            "",
            message,
            "",
        ]
        for k, v in details.items():
            lines.append(f"  {k}: {v}")
        return "\n".join(lines)

    # -- send --

    def send(
        self,
        alert_level: str,
        site_name: str,
        message: str,
        details: dict[str, Any],
    ) -> None:
        msg = EmailMessage()
        msg["Subject"] = f"[{alert_level}] GEWS Alert -- {site_name}"
        msg["From"] = self.from_addr
        msg["To"] = ", ".join(self.to_addrs)

        plain = self._format_plain(alert_level, site_name, message, details)
        html = self._format_html(alert_level, site_name, message, details)

        msg.set_content(plain)
        msg.add_alternative(html, subtype="html")

        if self.smtp_port == 465:
            ctx = ssl.create_default_context()
            server = smtplib.SMTP_SSL(
                self.smtp_host, self.smtp_port,
                context=ctx, timeout=self.timeout,
            )
        else:
            server = smtplib.SMTP(
                self.smtp_host, self.smtp_port, timeout=self.timeout,
            )
            server.starttls(context=ssl.create_default_context())

        try:
            if self.username:
                server.login(self.username, self.password)
            server.send_message(msg)
        finally:
            server.quit()


# ---------------------------------------------------------------------------
# Slack channel
# ---------------------------------------------------------------------------


class SlackChannel(AlertChannel):
    """Slack incoming-webhook alerts using Block Kit formatting."""

    name = "slack"

    def __init__(self, webhook_url: str, timeout: int = 30) -> None:
        self.webhook_url = webhook_url
        self.timeout = timeout

    @classmethod
    def from_config(cls, cfg: dict) -> "SlackChannel | None":
        url = cfg.get("webhook_url", "")
        if not url:
            logger.warning("Slack channel: webhook_url missing; skipping")
            return None
        return cls(
            webhook_url=url,
            timeout=int(cfg.get("timeout", 30)),
        )

    @staticmethod
    def _build_payload(
        alert_level: str,
        site_name: str,
        message: str,
        details: dict[str, Any],
    ) -> dict:
        level_emoji = {
            "INFO": ":information_source:",
            "WARNING": ":warning:",
            "CRITICAL": ":rotating_light:",
        }
        emoji = level_emoji.get(alert_level, ":bell:")
        detail_lines = "\n".join(f"*{k}:* {v}" for k, v in details.items())
        return {
            "text": f"{emoji} [{alert_level}] GEWS Alert -- {site_name}: {message}",
            "blocks": [
                {
                    "type": "header",
                    "text": {
                        "type": "plain_text",
                        "text": f"{emoji} [{alert_level}] GEWS Alert -- {site_name}",
                    },
                },
                {
                    "type": "section",
                    "text": {"type": "mrkdwn", "text": message},
                },
                {
                    "type": "section",
                    "text": {"type": "mrkdwn", "text": detail_lines},
                },
            ],
        }

    def send(
        self,
        alert_level: str,
        site_name: str,
        message: str,
        details: dict[str, Any],
    ) -> None:
        payload = self._build_payload(alert_level, site_name, message, details)
        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            self.webhook_url,
            data=data,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        urllib.request.urlopen(req, timeout=self.timeout)


# ---------------------------------------------------------------------------
# Generic webhook channel
# ---------------------------------------------------------------------------


class WebhookChannel(AlertChannel):
    """POSTs a JSON payload to an arbitrary URL."""

    name = "webhook"

    def __init__(
        self,
        url: str,
        headers: dict[str, str] | None = None,
        timeout: int = 30,
    ) -> None:
        self.url = url
        self.headers = headers or {}
        self.timeout = timeout

    @classmethod
    def from_config(cls, cfg: dict) -> "WebhookChannel | None":
        url = cfg.get("url", "")
        if not url:
            logger.warning("Webhook channel: url missing; skipping")
            return None
        return cls(
            url=url,
            headers=cfg.get("headers", {}),
            timeout=int(cfg.get("timeout", 30)),
        )

    @staticmethod
    def _build_payload(
        alert_level: str,
        site_name: str,
        message: str,
        details: dict[str, Any],
    ) -> dict:
        return {
            "alert_level": alert_level,
            "site_name": site_name,
            "message": message,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "details": details,
        }

    def send(
        self,
        alert_level: str,
        site_name: str,
        message: str,
        details: dict[str, Any],
    ) -> None:
        payload = self._build_payload(alert_level, site_name, message, details)
        data = json.dumps(payload).encode("utf-8")
        headers = {"Content-Type": "application/json", **self.headers}
        req = urllib.request.Request(
            self.url, data=data, headers=headers, method="POST",
        )
        urllib.request.urlopen(req, timeout=self.timeout)


# ---------------------------------------------------------------------------
# Dispatcher
# ---------------------------------------------------------------------------

# Maps config key -> channel factory
_CHANNEL_FACTORIES: dict[str, type[AlertChannel]] = {
    "email": EmailChannel,
    "slack": SlackChannel,
    "webhook": WebhookChannel,
}


class AlertDispatcher:
    """Fan-out dispatcher: sends an alert to every configured channel,
    logging failures without crashing the monitoring loop.

    Returns per-channel success/failure so the caller can decide whether
    to mark an alert as "sent" or retry on the next cycle.
    """

    def __init__(self, channels: list[AlertChannel] | None = None) -> None:
        self.channels: list[AlertChannel] = channels or []

    @classmethod
    def from_config(cls, site_config: dict) -> "AlertDispatcher":
        """Build a dispatcher from the ``alerts:`` section of a site
        config (already env-expanded or not — we expand here)."""
        raw = site_config.get("alerts", {})
        if not raw:
            return cls()

        expanded = expand_env_vars(raw)
        channels: list[AlertChannel] = []

        for key, cfg in expanded.items():
            factory = _CHANNEL_FACTORIES.get(key)
            if factory is None:
                logger.warning("Unknown alert channel %r; skipping", key)
                continue
            if not isinstance(cfg, dict):
                logger.warning("Alert channel %r config is not a dict; skipping", key)
                continue
            channel = factory.from_config(cfg)  # type: ignore[attr-defined]
            if channel is not None:
                channels.append(channel)

        return cls(channels)

    def dispatch(
        self,
        alert_level: str,
        site_name: str,
        message: str,
        details: dict[str, Any],
    ) -> dict[str, bool]:
        """Send the alert to every configured channel.

        Returns a dict mapping channel name to success (True/False).
        An empty dict means no channels were configured (no-op).
        """
        results: dict[str, bool] = {}
        for channel in self.channels:
            try:
                channel.send(alert_level, site_name, message, details)
                results[channel.name] = True
                logger.info(
                    "Alert sent via %s for [%s] %s",
                    channel.name, site_name, alert_level,
                )
            except Exception:
                results[channel.name] = False
                logger.exception(
                    "Failed to send alert via %s for [%s]",
                    channel.name, site_name,
                )
        return results
