"""
InSAR processing module — wraps ISCE-2 and MintPy for interferogram
generation and time-series inversion.

This module generates the configuration files and orchestrates the
processing workflow. The actual InSAR computation is performed by
ISCE-2 (interferograms) and MintPy (time-series inversion).

Prerequisites:
    - ISCE-2 installed (https://github.com/isce-framework/isce2)
    - MintPy installed (https://github.com/insarlab/MintPy)
    - SNAPHU installed for phase unwrapping

Usage:
    from gews.process import InSARProcessor

    proc = InSARProcessor(config)
    proc.prepare_stack()       # Generate ISCE-2 stack configuration
    proc.run_isce()            # Run interferogram generation
    proc.run_mintpy()          # Run time-series inversion
    ts = proc.load_timeseries()  # Load displacement time series
"""

from __future__ import annotations

import json
import logging
import subprocess
import textwrap
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np

logger = logging.getLogger(__name__)


@dataclass
class DisplacementTimeseries:
    """
    Container for InSAR displacement time-series data.

    Attributes
    ----------
    dates : np.ndarray
        Acquisition dates as ordinal days (shape: [n_dates]).
    date_strings : list[str]
        ISO date strings corresponding to each time step.
    displacement : np.ndarray
        Line-of-sight displacement in meters (shape: [n_dates, n_rows, n_cols]).
        Positive = motion toward satellite (uplift or away from slope).
        Negative = motion away from satellite (subsidence or downslope).
    velocity : np.ndarray
        Mean LOS velocity in m/yr (shape: [n_rows, n_cols]).
    temporal_coherence : np.ndarray
        Temporal coherence (shape: [n_rows, n_cols]), range [0, 1].
    latitude : np.ndarray
        Latitude grid (shape: [n_rows, n_cols]).
    longitude : np.ndarray
        Longitude grid (shape: [n_rows, n_cols]).
    metadata : dict
        Processing metadata (reference point, wavelength, etc.).
    """

    dates: np.ndarray
    date_strings: list[str]
    displacement: np.ndarray
    velocity: np.ndarray
    temporal_coherence: np.ndarray
    latitude: np.ndarray
    longitude: np.ndarray
    metadata: dict


class InSARProcessor:
    """
    Orchestrates InSAR processing from SLC scenes to displacement
    time series.

    The processor generates configuration files for ISCE-2's
    topsStack and MintPy, runs them as subprocesses, and loads
    the results into a DisplacementTimeseries object for downstream
    analysis.
    """

    def __init__(self, config: dict):
        self.config = config
        self.site = config["site"]
        self.proc = config["process"]

        self.slc_dir = Path(config["acquire"].get("output_dir", "data/slc"))
        self.work_dir = Path("data/isce_work")
        self.mintpy_dir = Path(self.proc["mintpy"].get("output_dir", "data/mintpy"))

    def prepare_stack(self) -> Path:
        """
        Generate ISCE-2 topsStack run files for the SLC stack.

        Creates the configuration and run scripts that ISCE-2 uses
        to process the interferogram network.

        Returns
        -------
        Path
            Path to the generated run_files directory.
        """
        self.work_dir.mkdir(parents=True, exist_ok=True)

        net = self.proc["network"]
        dem = self.proc["dem_source"]
        unwrap = self.proc["unwrapping"]

        # Find the DEM file or trigger download
        dem_file = self._get_dem()

        # Build topsStack command
        cmd = [
            "stackSentinel.py",
            "-s", str(self.slc_dir.resolve()),
            "-d", str(dem_file),
            "-o", str((self.work_dir / "orbits").resolve()),
            "-a", str((self.work_dir / "aux_cal").resolve()),
            "-w", str(self.work_dir.resolve()),
            "-C", "geometry",  # co-registration method
            "-W", unwrap["method"],
            "-m", unwrap["init_method"],
            "-t", str(net["max_temporal_baseline_days"]),
            "-b", str(net["max_perpendicular_baseline_m"]),
            "--num_connections", "3" if net["method"] == "sequential" else "all",
        ]

        # Write the command for reference
        cmd_file = self.work_dir / "stack_command.sh"
        cmd_file.write_text(
            "#!/bin/bash\n"
            "# Generated by GEWS — run this to create ISCE-2 processing scripts\n"
            f"cd {self.work_dir.resolve()}\n"
            f"{' '.join(cmd)}\n"
        )
        cmd_file.chmod(0o755)

        logger.info("Generated ISCE-2 stack configuration at %s", cmd_file)
        logger.info(
            "Network: %s, max temporal baseline %d days, max perp baseline %d m",
            net["method"],
            net["max_temporal_baseline_days"],
            net["max_perpendicular_baseline_m"],
        )

        return self.work_dir / "run_files"

    def run_isce(self, dry_run: bool = False) -> None:
        """
        Execute the ISCE-2 processing stack.

        Runs the generated run_files in sequence. Each run file handles
        one processing step (co-registration, interferogram formation,
        unwrapping, geocoding).

        Parameters
        ----------
        dry_run : bool
            If True, print commands without executing.
        """
        run_dir = self.work_dir / "run_files"

        if not run_dir.exists():
            raise FileNotFoundError(
                f"Run files not found at {run_dir}. "
                "Call prepare_stack() first."
            )

        run_files = sorted(run_dir.glob("run_*"))
        logger.info("Found %d ISCE-2 run files", len(run_files))

        for rf in run_files:
            logger.info("Running %s", rf.name)
            if dry_run:
                logger.info("  [DRY RUN] Would execute: bash %s", rf)
                continue

            result = subprocess.run(
                ["bash", str(rf)],
                cwd=str(self.work_dir),
                capture_output=True,
                text=True,
            )

            if result.returncode != 0:
                logger.error("ISCE-2 step failed: %s", rf.name)
                logger.error("STDERR: %s", result.stderr[-2000:])
                raise RuntimeError(
                    f"ISCE-2 processing failed at {rf.name}. "
                    f"Check logs in {self.work_dir}"
                )

        logger.info("ISCE-2 processing complete")

    def generate_mintpy_config(self) -> Path:
        """
        Generate MintPy configuration file for time-series inversion.

        Returns
        -------
        Path
            Path to the generated smallbaselineApp.cfg file.
        """
        self.mintpy_dir.mkdir(parents=True, exist_ok=True)

        mp = self.proc["mintpy"]
        unwrap = self.proc["unwrapping"]

        # MintPy configuration — see MintPy docs for full parameter list
        cfg_content = textwrap.dedent(f"""\
            # MintPy configuration for GEWS PoC
            # Site: {self.site['name']}
            # Generated by gews.process

            ########## loading data ##########
            mintpy.load.processor      = isce
            mintpy.load.unwFile        = {self.work_dir}/merged/interferograms/*/filt_fine.unw
            mintpy.load.corFile        = {self.work_dir}/merged/interferograms/*/filt_fine.cor
            mintpy.load.connCompFile   = {self.work_dir}/merged/interferograms/*/filt_fine.unw.conncomp
            mintpy.load.demFile        = {self.work_dir}/merged/geom_reference/hgt.rdr
            mintpy.load.lookupYFile    = {self.work_dir}/merged/geom_reference/lat.rdr
            mintpy.load.lookupXFile    = {self.work_dir}/merged/geom_reference/lon.rdr
            mintpy.load.incAngleFile   = {self.work_dir}/merged/geom_reference/los.rdr
            mintpy.load.azAngleFile    = {self.work_dir}/merged/geom_reference/los.rdr
            mintpy.load.waterMaskFile  = {self.work_dir}/merged/geom_reference/waterMask.rdr

            ########## subset (optional) ##########
            # Uncomment to subset to a smaller area for faster processing
            # mintpy.subset.lalo = {self.site['latitude']-0.1}:{self.site['latitude']+0.1},{self.site['longitude']-0.1}:{self.site['longitude']+0.1}

            ########## reference point ##########
            mintpy.reference.lalo      = {_ref_point(mp)}

            ########## network inversion ##########
            mintpy.networkInversion.weightFunc = var
            mintpy.networkInversion.minTempCoh = {mp.get('min_temporal_coherence', 0.7)}

            ########## tropospheric correction ##########
            mintpy.troposphericDelay.method = {mp.get('tropospheric_correction', 'ERA5').lower()}

            ########## topographic residual ##########
            mintpy.topographicResidual = yes

            ########## velocity estimation ##########
            mintpy.velocity.startDate  = auto
            mintpy.velocity.endDate    = auto

            ########## geocoding ##########
            mintpy.geocode             = yes
            mintpy.geocode.SNWE        = auto
            mintpy.geocode.laloStep    = auto
        """)

        cfg_file = self.mintpy_dir / "smallbaselineApp.cfg"
        cfg_file.write_text(cfg_content)

        logger.info("Generated MintPy configuration at %s", cfg_file)
        return cfg_file

    def run_mintpy(self, dry_run: bool = False) -> None:
        """
        Execute MintPy time-series inversion.

        Parameters
        ----------
        dry_run : bool
            If True, print commands without executing.
        """
        cfg_file = self.mintpy_dir / "smallbaselineApp.cfg"
        if not cfg_file.exists():
            cfg_file = self.generate_mintpy_config()

        cmd = ["smallbaselineApp.py", str(cfg_file), "--dir", str(self.mintpy_dir)]

        logger.info("Running MintPy: %s", " ".join(cmd))

        if dry_run:
            logger.info("[DRY RUN] Would execute: %s", " ".join(cmd))
            return

        result = subprocess.run(cmd, capture_output=True, text=True)

        if result.returncode != 0:
            logger.error("MintPy failed")
            logger.error("STDERR: %s", result.stderr[-2000:])
            raise RuntimeError(
                f"MintPy processing failed. Check logs in {self.mintpy_dir}"
            )

        logger.info("MintPy processing complete. Output in %s", self.mintpy_dir)

    def load_timeseries(self, min_coherence: float | None = None) -> DisplacementTimeseries:
        """
        Load MintPy output into a DisplacementTimeseries object.

        Parameters
        ----------
        min_coherence : float or None
            Mask pixels below this temporal coherence. If None, uses
            config value.

        Returns
        -------
        DisplacementTimeseries
        """
        import h5py

        if min_coherence is None:
            min_coherence = self.proc["mintpy"].get("min_temporal_coherence", 0.7)

        ts_file = self.mintpy_dir / "geo" / "geo_timeseries_ERA5_ramp_demErr.h5"
        if not ts_file.exists():
            # Try without tropospheric correction suffix
            ts_file = self.mintpy_dir / "geo" / "geo_timeseries.h5"
        if not ts_file.exists():
            raise FileNotFoundError(
                f"MintPy time-series file not found in {self.mintpy_dir / 'geo'}. "
                "Run run_mintpy() first."
            )

        logger.info("Loading time series from %s", ts_file)

        with h5py.File(ts_file, "r") as f:
            displacement = f["timeseries"][:]  # [n_dates, n_rows, n_cols] in meters
            date_strings = [d.decode() for d in f["date"][:]]

        # Load velocity
        vel_file = self.mintpy_dir / "geo" / "geo_velocity.h5"
        with h5py.File(vel_file, "r") as f:
            velocity = f["velocity"][:]

        # Load temporal coherence
        coh_file = self.mintpy_dir / "geo" / "geo_temporalCoherence.h5"
        with h5py.File(coh_file, "r") as f:
            coherence = f["temporalCoherence"][:]

        # Load coordinate grids
        geom_file = self.mintpy_dir / "geo" / "geo_geometryRadar.h5"
        with h5py.File(geom_file, "r") as f:
            latitude = f["latitude"][:]
            longitude = f["longitude"][:]

        # Parse dates to ordinal
        from datetime import datetime

        dates = np.array([
            datetime.strptime(d, "%Y%m%d").toordinal() for d in date_strings
        ])

        # Apply coherence mask
        mask = coherence < min_coherence
        displacement[:, mask] = np.nan
        velocity[mask] = np.nan

        n_valid = np.count_nonzero(~mask)
        n_total = mask.size
        logger.info(
            "Loaded %d dates × %d×%d pixels, %d valid (%.1f%%, coherence ≥ %.2f)",
            len(date_strings),
            displacement.shape[1],
            displacement.shape[2],
            n_valid,
            100 * n_valid / n_total,
            min_coherence,
        )

        return DisplacementTimeseries(
            dates=dates,
            date_strings=date_strings,
            displacement=displacement,
            velocity=velocity,
            temporal_coherence=coherence,
            latitude=latitude,
            longitude=longitude,
            metadata={
                "source_file": str(ts_file),
                "min_coherence": min_coherence,
                "wavelength_m": 0.05546,  # Sentinel-1 C-band
                "reference_point": self.proc["mintpy"].get("reference_point", "auto"),
            },
        )

    def _get_dem(self) -> Path:
        """Download or locate DEM for the study area."""
        dem_dir = self.work_dir / "dem"
        dem_dir.mkdir(parents=True, exist_ok=True)
        dem_file = dem_dir / "dem.wgs84"

        if dem_file.exists():
            logger.info("Using existing DEM: %s", dem_file)
            return dem_file

        # Use ISCE-2's dem.py to download SRTM
        lat = self.site["latitude"]
        lon = self.site["longitude"]
        buf = self.site.get("buffer_km", 15) / 111.0

        cmd = [
            "dem.py",
            "-a", "stitch",
            "-b", f"{lat-buf}", f"{lat+buf}", f"{lon-buf}", f"{lon+buf}",
            "-r", "-s", "1",  # 1 arc-second SRTM
            "-c", "-f",
        ]

        logger.info("Downloading DEM for %.2f°N, %.2f°E ± %.0f km", lat, lon, buf * 111)

        result = subprocess.run(
            cmd, cwd=str(dem_dir), capture_output=True, text=True
        )

        if result.returncode != 0:
            logger.warning(
                "Automatic DEM download failed. Download manually and place at %s",
                dem_file,
            )
            logger.debug("STDERR: %s", result.stderr[:500])

        return dem_file


def _ref_point(mp_config: dict) -> str:
    """Format reference point for MintPy config."""
    ref = mp_config.get("reference_point", "auto")
    if ref == "auto":
        return "auto"
    if isinstance(ref, (list, tuple)) and len(ref) == 2:
        return f"{ref[0]},{ref[1]}"
    return str(ref)
