apiVersion: v1
kind: Service
metadata:
  name: gews-dashboard
  namespace: gews
  labels:
    app.kubernetes.io/name: gews
    app.kubernetes.io/component: dashboard
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gews
    app.kubernetes.io/component: dashboard
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
